### ISSUE TITLE
FDR q-value scale reported incorrectly on Global Plot

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/gsea-desktop#10]
The Plot of p-values vs. NES in the Global statistics and plots section presents FDR qvaues as a 0-100 value rather than a 0-1 value as is the case for both standard p-values, and the FDR result on the results page itself. The reporting of this value should be consistent and reflect the standard accepted 0-1 scale.

![pvalues_vs_nes_plot](https://user-images.githubusercontent.com/26012303/62398533-d8fb1480-b52d-11e9-8377-f113150e4531.png)

**Comment by davideby** [comment]
Fixed in the 4.2.x releases.
