### ISSUE TITLE
Reorder items in Gene sets database dialogue

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/gsea-desktop#20]
Currently in the dialogue to select the Gene sets database the order is "Gene matrix (from website)" then "Gene sets (grp)" then "Gene matrix (local gmx/gmt)". In the default window dimensions, this dialogue only the first two items are visible. As a local data file is much more commonly used than a grp file of a single gene set, it would be more intuitive for users to have the position of these two items switched in the window such that how to access the local files can be seen without the user needing to do anything.

**Comment by davideby** [comment]
Fixed in 4.0.3
