### ISSUE TITLE
Problem with Downloads > Download chip annotations

### ISSUE THREAD

**Issue by helgathorv** [GSEA-MSigDB/gsea-desktop#25]
Selecting 'Downloads > Download chip annotations' from the menu bar tries to connect to the ftp site. It should go to the same place as when you click on 'view chip files' on the website, i.e. to https://data.broadinstitute.org/gsea-msigdb/msigdb/annotations_versioned/

**Comment by davideby** [comment]
Fixed in the 4.2.x releases.
