### ISSUE TITLE
Unable to find cytoscape

### ISSUE THREAD

**Issue by sebastian-luna-valero** [GSEA-MSigDB/gsea-desktop#3]
Hello,

When I click on the `Enrichment Map Map Visualization` button in GSEA (3.0), it says: `Unable to find cytoscape`. Please see the the screen-shot below:

![gsea-issue](https://user-images.githubusercontent.com/5345517/35621004-d702dc20-067a-11e8-80dc-702345f0e23e.png)

However, `cytoscape` is installed on my system and available in the `$PATH`. 

Moreover, when I choose `locate` in the dialog menu and I select the installation folder for `cytoscape` I get `Chosen location is not a recognized Cytoscape path: <install-dir>`

Could you please let me know how to proceed?

Many thanks,
Sebastian

**Comment by sebastian-luna-valero** [comment]
Below is the full error message:
```
<Error Details>

---- Full Error Message ----
Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/cytoscape-3.3.0

---- Stack Trace ----
# of exceptions: 1
------Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/cytoscape-3.3.0------
edu.mit.broad.cytoscape.CytoscapeLocationSingleton$CytoscapeDownloadException: Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/cytoscape-3.3.0
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.RedirectCytoscapeDownload(CytoscapeLocationSingleton.java:230)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.getCytoscapeLocation(CytoscapeLocationSingleton.java:122)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.<init>(CytoscapeLocationSingleton.java:56)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.getInstance(CytoscapeLocationSingleton.java:37)
	at edu.mit.broad.cytoscape.CytoscapeLaunch.launch(CytoscapeLaunch.java:54)
	at edu.mit.broad.cytoscape.action.EnrichmentMapInputPanelAction.getWidget(EnrichmentMapInputPanelAction.java:37)
	at edu.mit.broad.xbench.actions.WidgetAction$2.run(WidgetAction.java:126)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by davideby** [comment]
Hi Sebastian,

The code that makes that path check works from a hard-coded pattern for the name of the Cytoscape location.  For that directory name, it expects to see "Cytoscape_v" followed by a three-part version number (like "3.3.0" in this case) which it uses to make sure the version of Cytoscape is sufficient.

So what's happening here is that the code is not recognizing the directory because of the leading "cytoscape-" where it expects "Cytoscape_v".  Renaming the directory ought to solve the issue.

The code originally came from a Cytoscape developer, but I'll make a note in our bug-tracking system to see if we can find a better way to test this in a future release.

Regards,
David

**Comment by sebastian-luna-valero** [comment]
Hi David,

Many thanks for your reply!

I created a symlink with the expected directory name (just to avoid re-installation for the time being), but I have the get the same error:
```
<Error Details>

---- Full Error Message ----
Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/Cytoscape-v3.3. ...

---- Stack Trace ----
# of exceptions: 1
------Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/Cytoscape-v3.3.0------
edu.mit.broad.cytoscape.CytoscapeLocationSingleton$CytoscapeDownloadException: Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/Cytoscape-v3.3.0
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.RedirectCytoscapeDownload(CytoscapeLocationSingleton.java:230)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.getCytoscapeLocation(CytoscapeLocationSingleton.java:122)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.<init>(CytoscapeLocationSingleton.java:56)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.getInstance(CytoscapeLocationSingleton.java:37)
	at edu.mit.broad.cytoscape.CytoscapeLaunch.launch(CytoscapeLaunch.java:54)
	at edu.mit.broad.cytoscape.action.EnrichmentMapInputPanelAction.getWidget(EnrichmentMapInputPanelAction.java:37)
	at edu.mit.broad.xbench.actions.WidgetAction$2.run(WidgetAction.java:126)
	at java.lang.Thread.run(Thread.java:748)
```

I wonder whether it is expecting something else within the installation directory?

Best regards,
Sebastian

**Comment by davideby** [comment]
Hi Sebastian,

Note that it's "Cytoscape_v" instead of "Cytoscape-v".

- David

**Comment by sebastian-luna-valero** [comment]
Thanks David, and apologies for missing that out.

I recreated the symlink with `Cytoscape_v` but still does not like it:
```
<Error Details>

---- Full Error Message ----
Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/Cytoscape_v3.3. ...

---- Stack Trace ----
# of exceptions: 1
------Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/Cytoscape_v3.3.0------
edu.mit.broad.cytoscape.CytoscapeLocationSingleton$CytoscapeDownloadException: Chosen location is not a recognized Cytoscape path:/ifs/apps/bio/Cytoscape_v3.3.0
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.RedirectCytoscapeDownload(CytoscapeLocationSingleton.java:230)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.getCytoscapeLocation(CytoscapeLocationSingleton.java:122)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.<init>(CytoscapeLocationSingleton.java:56)
	at edu.mit.broad.cytoscape.CytoscapeLocationSingleton.getInstance(CytoscapeLocationSingleton.java:37)
	at edu.mit.broad.cytoscape.CytoscapeLaunch.launch(CytoscapeLaunch.java:54)
	at edu.mit.broad.cytoscape.action.EnrichmentMapInputPanelAction.getWidget(EnrichmentMapInputPanelAction.java:37)
	at edu.mit.broad.xbench.actions.WidgetAction$2.run(WidgetAction.java:126)
	at java.lang.Thread.run(Thread.java:748)
```

Best regards,
Sebastian

**Comment by davideby** [comment]
Hi Sebastian,

I just had a closer look at the code and it looks like a symbolic link won't help.  It's using a Java call ( File.getCanonicalPath() ) that determines the path in its canonical form for the platform, including resolving '.', '..', and the actual target of symbolic links.

Sorry I didn't notice that earlier.  I'm pretty sure that renaming the directory will take care of it, but if that's not possible then try a hard link instead, using 'ln' without the the '-s' flag.

Hope this helps.  Let me know if you still have trouble.
Thanks,
David

**Comment by sebastian-luna-valero** [comment]
Hi David,

Many thanks again for your valuable input. That's working now!

Best regards,
Sebastian

**Comment by Tamizhini1997** [comment]
Sir, I also got the same error of GSEA-Cytoscape plugin not opened. How to rectify this sir.

**Comment by davideby** [comment]
Hi,

Did you try the fixes described?  What happened?

If you are seeing a different error please open a new issue instead of reposting in this current thread.  That will will help more people find useful information in the future.  

You might also want to post on our [GSEA Forum](https://groups.google.com/g/gsea-help) instead as your issue will be seen by more people there.

**Comment by Tamizhini1997** [comment]
![error_gsea](https://user-images.githubusercontent.com/70936790/92563463-3c10bc00-f295-11ea-9c68-85f36ddb111d.png)
Hi sir, i upload the error of my screenshot.It says the Cytoscape couldn't launch for enrichment map.

**Comment by davideby** [comment]
No, it says "Please launch Cytoscape 3.3+ with the Enrichment Map plug-in before continuing."  Did you do that?

We changed this integration in v4.0.0 to have the user launch Cytoscape outside of GSEA to avoid problems launching due to platform-specific issues, newer Cytoscape versions, multiple installations, custom installations, and so on.  This is explained in the [Release Notes](http://software.broadinstitute.org/cancer/software/gsea/wiki/index.php/GSEA_v4.0.x_Release_Notes#GSEA_Desktop_v4.0.0_.28Aug_2019.29).

Again, if you are having a different problem than the original question, please post with a new issue instead of reposting in this current thread.

**Comment by Tamizhini1997** [comment]
yes sir. I launched Cytoscape 3.7.0 and GSEA v4.0.0.But then it couldn't
open cytoscape.

**Comment by davideby** [comment]
Hi @Tamizhini1997 ,

Sorry for the delay in responding.  I've been traveling and we've been working on a big release so I haven't had a chance to look at this in more detail.

Unfortunately, you haven't given us enough details from which we can figure out the issue.  I can't reproduce the problem in my tests, so without further information there's nothing we can do but guess.

The [Contact page](https://www.gsea-msigdb.org/gsea/contact.jsp) of our website gives a list of information that might be useful to us in error reports.  In particular, **your data** is most likely the crucial missing piece here.  That web page lists an email address where data can be sent to keep it private.  We would need a ZIP bundle of the GSEA analysis folder you are trying to use for the Enrichment Map analysis.

**Please do not respond to this Issue thread, as I've said multiple times.**  Whatever issue you have is **not** the same as the original one.  Open a **new** one, either in [GitHub Issues](https://github.com/GSEA-MSigDB/gsea-desktop/issues/new/choose) or on [our Forum](https://groups.google.com/group/gsea-help).

I will be locking **this** thread for further edits.
