### ISSUE TITLE
Build Enrichment Map doesn't work.

### ISSUE THREAD

**Issue by githubtefo** [GSEA-MSigDB/gsea-desktop#4]
macOS High Sierra (v10.13.3)
GSEA v.3.0 [build 0160]
Cytoscape v.3.6.0
Java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
JavaHotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode).

When I click on "Enrichment Map Visualization the Cytoscape" opens, but then when I load the result folder and click on "Build Enrichment Map" nothing happens.

This is the log of that process:
```
< Process output will appear below >

Done initing things while splashing
INFO - /Applications/Cytoscape_v3.6.0
INFO - Latest version of cytoscape is:Cytoscape_v3.6.0
INFO - looking for prefix plugin:enrichmentmap
INFO - EM version installed:-1.0
java.io.IOException: Invalid signature file digest for Manifest main attributes
INFO - command issued:/Applications/Cytoscape_v3.6.0/cytoscape.sh -R 1234
INFO - Java home:/Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home
INFO - successfully connected to cytoscape rest
INFO - successfully connected to cytoscape rest
```
If I run `/Applications/Cytoscape_v3.6.0/cytoscape.sh -R 1234` on the console, the cytoscape opens, but with this output: "Unable to find any JVMs matching version 1.7".

Thank you for your support!

**Comment by davideby** [comment]
Hi,

This looks like there's an error when Cytoscape tries to launch, like maybe it's trying to run an old version of the EnrichmentMap plug-in.  I'm sorry to say I can't be much help here.  My best suggestion is to contact the developers through theor Cytoscape App Store page:  http://apps.cytoscape.org/apps/enrichmentmap

Hope that helps,
David

**Comment by githubtefo** [comment]
I solved it. I needed to install and run the "Enrichment Map" plugin in Cytoscape before using it with GSEA.
My mistake, sorry about that.
Thank you
