### ISSUE TITLE
parameters .rpt not created when GSEA encounters Error

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/gsea-desktop#41]
When GSEA Errors out (tested with many of the common “early” errors, wrong/no chip, invalid ranking metric for data, probably others) the .rpt file containing the GSEA run parameters is not produced but is listed on the error'ed run’s index.html page.

Having this report would be useful for debugging user reports as it would allow us to see all the parameters necessary for reproducing their failed analysis run.

**Comment by davideby** [comment]
Fixed in the 4.2.x releases.
