### ISSUE TITLE
Abs.max in Collapse Dataset

### ISSUE THREAD

**Issue by ACastanza** [GSEA-MSigDB/gsea-desktop#42]
I can't remember if we discussed this, but support for picking a gene based on the maximum _absolute_ value would resolve the potential positive distribution bias when running in preranked mode, and could also provide some value to certain ssGSEA scenarios. I would also suggest making this the default in Preranked mode.

**Comment by davideby** [comment]
I kind of remember having a conversation about this and thinking it sounded reasonable.  I also seem to remember running it past Pablo, and maybe he had some concerns?  I'll see if I can find the old email.

**Comment by davideby** [comment]
I found the email but it looks like that was a conversation about a different concern.  I'll need to think about this one some more.
