### ISSUE TITLE
Question of mountain plot of GSEA

### ISSUE THREAD

**Issue by jiananwehi** [GSEA-MSigDB/gsea-desktop#44]
I want to make my own mountain plot for the purpose of publication. But I get stuck on the colored bar of the mountain plot, shown as follows:
<img width="493" alt="1" src="https://user-images.githubusercontent.com/76154106/121610494-854aa200-ca99-11eb-83d9-dd46f0d24e42.png">
I can understand blue means low rank metric, and red mean high rank metric. How does GSEA algorithm categorized continuous preranked metric into different categorical values?

**Comment by ACastanza** [comment]
Hi Jiananwehi,

I’ll have to look into this and get back to you. In the meantime, if you just need a higher quality figure, GSEA’s advanced parameters has an option to enable SVG plotting. Note: if you’re going to rerun GSEA, you’ll want to retrieve the random seed from the “comments” section of the index.html page and supply that to the “seed for permutation” parameter (also under advanced fields).

One thing that I noticed in your plot is that the Zero cross is at 691 and you appear to only have 1200 genes in your dataset. GSEA is designed to run on the entire expression dataset, not just a subset of differentially expressed genes, so we’d recommend reanalyzing with the entire dataset if you have it available. 

Finally, we generally provide support for GSEA over on our google group and not through github issues page, this page is more for technical issues with the software itself. You can find the group here: https://groups.google.com/forum/#!forum/gsea-help for future reference.
