### ISSUE TITLE
Timestamp RNG seed is sometimes not saved

### ISSUE THREAD

**Issue by davideby** [GSEA-MSigDB/gsea-desktop#47]
@ACastanza reported this, coming out of helping a user on the GSEA forums.  The user's analysis report index.html file had no timestamp listed in the Comments section even though they had not explicitly set an RNG seed.  While it's possible they might be incorrect and actually *had* set the seed value, since this is an Advanced Parameter it seems unlikely.

We can't replicate the bug and no one can say what steps might have led to it.

I also had a similar experience but in the opposite direction: I was running analyses and had GSEA get into a state where it *always* saved a timestamp seed value to the report, even though I *had* set the seed value.  Again, I have no idea what led to this situation, but it's quite likely the two are related.

**Comment by davideby** [comment]
I have a way to replicate this:

1. First run an analysis with the seed set to an explicit value.  
2. Then **erase the field value for the seed and leave it blank** and run a second analysis.  GSEA will run but keep the former seed value setting from the first run (you can see this by checking the RPT file).  
3. If you then change the seed back to `timestamp` it will continue to run using the **seed from the very first analysis** (i.e. the explicit value setting) and no timestamp will be printed in the report.  It will continue doing that on each analysis until you close the Desktop session and restart.

This is a fairly convoluted set of steps for a user to have performed, so I'm concerned there's some easier way to get into this situation that I haven't found yet.  OTOH, this is definitely a bug and fixing it might take care of it in general.

**Comment by ACastanza** [comment]
Sounds like it needs some logic to explicitly check the field at every run, set the integer value if one is present and if anything else, to force the current timestamp as the seed.

**Comment by davideby** [comment]
Yes, that's my guess.  Something along those lines anyway.  It might be as simple as making this as required field so the user can't leave it blank.  I'm not totally convinced of that, though, since I haven't looked at the code, just the behavior.

**Comment by davideby** [comment]
Fixed in the 4.2.x releases
