### ISSUE TITLE
What is a good Enrichment Score?

### ISSUE THREAD

**Issue by hukai916** [GSEA-MSigDB/gsea-desktop#55]
Hi developers,

I read from the manual that one can consider a set significantly enriched if its NES has an FDR q-value below 0.25. Then, how about the enrichment score? Do you also suggest a cutoff for the enrichment to make biological sense?

Thanks,

--Kai

**Comment by ACastanza** [comment]
Hi Kai,

We don't provide suggested cutoffs for the NES, it's entirely possible for relatively weak changes to have biological meaning. That said, what FDR you should use as a cutoff depends on what mode of GSEA you're running in, if you're running in Phenotype permutation mode, which recomends a minimum of seven samples per group, then the 0.25 cutoff is reasonable as that permutation method is extremely stringent. If you're using the gene set permutation mode or running GSEA Preranked which runs gene set permutation internally, then a more traditional 0.05 FDR cutoff is probably more reasonable.

In the future, we'd ask that these sorts of questions get posted to the GSEA Help forum: https://groups.google.com/forum/#!forum/gsea-help, we only really use GitHub issues for reporting technical issues with the GSEA software itself.

I'm going to close this issue, but if you have more questions feel free to reach out to us at the GSEA Help forum, or you can reply here but that might take us a little longer to see.

-Anthony
Anthony S. Castanza, PhD
Curator, Molecular Signatures Database
Mesirov Lab, Department of Medicine
University of California, San Diego

**Comment by hukai916** [comment]
Thank you very much, it makes sense, I will post further question to the
help site in the future.
