### ISSUE TITLE
Order effects

### ISSUE THREAD

**Issue by Lila14** [GSEA-MSigDB/gsea-desktop#6]
I tested reversing the order of phenotype labels. I reversed the order of GFP and TAM_KO in both the .cls and .gct, which I thought shouldn't affect the output (see attached). But it changed the output (see attached). A number of genes were reversed: genes that had been upregulated in GFP are now said to be upregulated in TAM_KO and vice versa. What's going on?

Auto-generated command: 

`java -Xmx512m xtools.gsea.Gsea -res /home/lur159/Documents/elcheva/EB1_iPSC-GFP-TAM_KO_counts_reversed.gct -cls /home/lur159/Documents/elcheva/EB1_iPSC-GFP-TAM_KO_reversed.cls#EB1_iPSC_TAM_KO_versus_EB1_iPSC_GFP -gmx /home/lur159/Documents/elcheva/GENE_LIST_RNAseq_exampleIE.gmt -collapse false -mode Max_probe -norm meandiv -nperm 1000 -permute phenotype -rnd_type no_balance -scoring_scheme weighted -rpt_label my_analysis -metric Ratio_of_Classes -sort real -order descending -create_gcts false -create_svgs false -include_only_symbols true -make_sets true -median false -num 100 -plot_top_x 20 -rnd_seed timestamp -save_rnd_lists false -set_max 500 -set_min 0 -zip_report false -out /home/lur159/gsea_home/output/may29 -gui false`

(The reason I use the .txt extension is because Github won't let me upload other file formats. I don't use this extension when running GSEA). 

[EB1_iPSC-GFP-TAM_KO.cls.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051724/EB1_iPSC-GFP-TAM_KO.cls.txt)
[EB1_iPSC-GFP-TAM_KO_counts.gct.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051725/EB1_iPSC-GFP-TAM_KO_counts.gct.txt)
[EB1_iPSC-GFP-TAM_KO_counts_reversed.gct.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051726/EB1_iPSC-GFP-TAM_KO_counts_reversed.gct.txt)
[EB1_iPSC-GFP-TAM_KO_reversed.cls.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051727/EB1_iPSC-GFP-TAM_KO_reversed.cls.txt)
[GENE_LIST_RNAseq_exampleIE.gmt.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051728/GENE_LIST_RNAseq_exampleIE.gmt.txt)
[gsea_report_for_EB1_iPSC_GFP.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051739/gsea_report_for_EB1_iPSC_GFP.txt)
[gsea_report_for_EB1_iPSC_GFP_reversed.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051740/gsea_report_for_EB1_iPSC_GFP_reversed.txt)
[gsea_report_for_EB1_iPSC_TAM_KO.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051741/gsea_report_for_EB1_iPSC_TAM_KO.txt)
[gsea_report_for_EB1_iPSC_TAM_KO_reversed.txt](https://github.com/GSEA-MSigDB/gsea-desktop/files/2051742/gsea_report_for_EB1_iPSC_TAM_KO_reversed.txt)

**Comment by davideby** [comment]
Sorry @Lila14 , this got lost in shuffle.  Please post these kinds of usage questions on our [GSEA Forum](https://groups.google.com/group/gsea-help) as they're otherwise likely to get missed.  They'll definitely be seen more broadly there.

We'll try to do better at watching this space, but it's really more suited for development chatter and questions about the code.
