### ISSUE TITLE
Cytoscape not working through GSEA

### ISSUE THREAD

**Issue by sraorao** [GSEA-MSigDB/gsea-desktop#7]
Hi, 

I am trying to generate an Enrichment Map Visualisation in GSEA, but when I click on "Build Enrichment Map", I get an error dialog that says `Cytoscape appears to have been closed. Just re-launching. Once it starts please try again to load your network.` and the terminal messages are as follows:
```
4078 [INFO ] Unable to communicate with cytoscape:Connection refused (Connection refused)
4078 [INFO ] looking for prefix plugin:enrichmentmap
4079 [INFO ] EM version installed:2.1
4079 [INFO ] command issued:/opt/Cytoscape_v3.6.1/cytoscape.sh -R 1234
4080 [INFO ] command issued:/opt/Cytoscape_v3.6.1/cytoscape.sh -R 1234crashed.Cannot run program "/usr/libexec/java_home": error=2, No such file or directory
4158 [INFO ] Cytoscape appears to have been closed.  Just re-launching. Once it starts please try again to load your network
```

Cytoscape is in the path, and starts when the command `/opt/Cytoscape_v3.6.1/cytoscape.sh -R 1234` is entered in the terminal. I am not sure why it is looking for `/usr/libexec/java_home` as that doesn't exist in Ubuntu. Also, just running Cytoscape separately and loading the gmt, rnk and cls files from the GSEA run seems to generate the network visualisation fine. 

OS: Ubuntu 16.04
java version "1.8.0_181"
$JAVA_HOME (set in .bashrc): /usr/lib/jvm/java-1.8.0-openjdk-amd64

Please let me know if you have seen this problem before or if something strikes you as odd in my setup?

Thanks!

**Comment by davideby** [comment]
Thanks for pointing this out, it's definitely a bug.  Yes, you're right: `/usr/libexec/java_home` is a macOS concept and doesn't apply here.  We have limited resources so this must have slipped through the cracks in our testing.

We're working on an update now.  So far it's almost purely focused on issues around the Java 8 -> Java 11 transition, but I'll be sure to add this to our ToDo list.

In the meantime, one possible workaround would be to launch Cytoscape separately and try to load up the required file through the [Enrichment Map plug-in](http://www.baderlab.org/Software/EnrichmentMap) there.

**Comment by davideby** [comment]
This will be fixed in an upcoming release: we'll just prompt the user to launch Cytoscape before connecting.
