### ISSUE TITLE
Cytoscape version number comparison not correct

### ISSUE THREAD

**Issue by mikekucera** [GSEA-MSigDB/gsea-desktop#9]
Cytoscape version numbers are not compared correctly and sometimes the wrong version is launched. 

Problem is here:
https://github.com/GSEA-MSigDB/gsea-desktop/blob/60835bf6ff0869f2072b30e0551c170dc9b319e2/src/edu/mit/broad/cytoscape/CytoscapeLocationSingleton.java#L171

The major, minor, and point parts of the version number are compared on equal footing. The result depends on the order of the cyto_list array. If 3.7.0 comes after 3.6.1 in the array it should pick 3.7.0, but if 3.7.0 comes before 3.6.1 then it will pick 3.6.1. The list of versions comes from the java.io.File.list() method, and the javadoc makes no mention of how the returned array is ordered, so its probably platform dependent.

It should compare the major version first, then only if those are equal compare the minor version, and so on.

**Comment by davideby** [comment]
Thanks, @mikekucera.  We're fixing this in a different way in an upcoming release by getting rid of the auto-launch entirely.  We'll just prompt the user to launch Cytoscape before attempting to connect to it.
